extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest
  - plugin:storybook/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended

env:
  node: true

ignorePatterns:
  - dist

rules:
  react-hooks/exhaustive-deps: error

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: tsconfig.json

    rules:
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-unsafe-member-access": off

  - files: ["*.stories.tsx"]
    rules:
      "filenames/match-exported": off

settings:
  react:
    version: detect
